name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
    
    - name: FTP Deployer
      # You may pin to the exact commit or the version.
      # uses: sand4rt/ftp-deployer@b4d8a88f104b46a1bcfac8f69b3413986cc0ce28
      uses: sand4rt/ftp-deployer@v1.3
      with:
        # SFTP on
        sftp: false # optional
        # FTP host URL like: ftp.host.com or sftp.host.com
        host: ${{ secrets.FTP_HOST }}
        # FTP port
        port: 21# optional, default is 21
        # Ftp username
        username: ${{ secrets.FTP_USERNAME }}
        # Ftp password
        password: ${{ secrets.FTP_PASSWORD }}
        # The remote folder location of your FTP server
        remote_folder: ${{ secrets.FTP_DIR }} # optional
        # The local folder location
        local_folder: dist # optional, default is dist
        # Remove existing files inside FTP remote folder
        cleanup: true # optional
        # includes
        include: [] # optional
        # exclude
        exclude: [] # optional
        # passive
        pasive: true # optional