name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
    
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: false
        host: ${{ secrets.FTP_HOST }}
        port: 21
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote_folder: ${{ secrets.FTP_DIR }}
        local_folder: dist
        cleanup: true
        pasive: true